### ISSUE TITLE
Problem downloading episodes on Pocketcast

### ISSUE THREAD

**Issue by kalpeshp0310** [artem-zinnatullin/TheContext-Podcast#64] opened 2017-04-12 07:14 UTC
Pocketcast always gives `handshake failed` error, when I try to download episodes.

**Comment by sockeqwe** [comment] 2017-04-12 07:37
Thanks for reporting.

Unfortunately this is a known issue.
We have added a note to the [show nodes](https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_9_Part1.md)

> Important note for Pocket Casts app users: Unfortunately Pocket Casts android app has a problem with downloading our episodes (to listen to them offline). It seems that while downloading their android app is using a old http client which doesn't support latest TLS cipher standards we use on server side to host our episodes.
>
> Nevertheless, streaming our episodes (instead of downloading) works in Pocket Casts android app.
>
> See this tutorial: [Pocket Casts: Streaming](http://support.pocketcasts.com/article/streaming-episodes/)

It seems that it is caused by a SSL cipher bug introduced Android 7.0.0 - fixed in Android 7.1.1.
What android version do you have on your device?

We are in contact with Pocket Casts and are hoping to fix this issue soon.

Meanwhile, you can stream the episodes through pocket casts.

**Comment by kalpeshp0310** [comment] 2017-04-12 08:58
@sockeqwe Thanks for the info and for the awesome podcasts :)
And yes, I am on Android 7.0

**Comment by artem-zinnatullin** [comment] 2017-04-12 10:12
So the issue is resolved for now, but not with greatest solution. We were able to keep TLS, but had to switch `ssl_ecdh_curve` to `prime256v1` which is [not *secure* option](https://github.com/nodejs/node/issues/1495), so we aim to change it back to `secp384r1` asap.

Thanks PocketCasts team for investigation, hopefully they'll be able to fix it on their side.

**Closed by artem-zinnatullin** 2017-04-12 10:12 UTC
Labels: bug

**Comment by kalpeshp0310** [comment] 2017-04-12 11:23
Thanks, I am able to download episodes now. :thumbsup:

**Comment by mvs3d** [comment] 2017-04-24 13:41
Hey all! I hate this error, this happened last one-two month for several my podcasts.. I'm try find decision, (found this thread in this way).. but no any simple instructions found. Re-subscription doesn't work too. 

And...sorry for off-topic but, at result I'm just switched to "Podcast & Radio Addict" application.. this is really cool app ;)

**Comment by sockeqwe** [comment] 2017-04-24 13:55
@mvs3d This issue seems to be caused by a bug in Android 7.+ (should be fixed in 7.1.1) and elliptic curve powered SSL and Pocket Casts (not sure why it works on other podcast players).

At least for our podcast it seems to be working or isn't download working in Pocket Casts for our podcast on your device?

**Comment by mvs3d** [comment] 2017-04-24 14:02
Well, i'm have this issue on my Galaxy S7 with last updates (Android 7.0 for now).

RSS to podcast I have issue: http://feeds.rucast.net/Umputun (there https links to mp3 files really)
RSS to podcast where NO issue (same authors, but looks like no HTTPS there): http://feeds.rucast.net/radio-t

I'm use SD card for destination folder.

**Comment by TheRealIndru** [comment] 2017-06-25 19:29
I have this exact problem on Android 5.0. Any fixes or solutions? My tablet does not support newer Android versions.

**Comment by sockeqwe** [comment] 2017-06-25 20:15
Isn't it working for our podcast? We changed the certificate on our server
and then it was (and still is) working at least on our devices (it wasn't
working on our devices previously)

TheRealIndru <notifications@github.com> schrieb am So., 25. Juni 2017,
21:29:
